### ISSUE TITLE
hcRNG not building

### ISSUE THREAD

**Issue by adityaatluri** [ROCmSoftwarePlatform/hcRNG#2]
Hi,
I tried to build hcRNG by running ./build.sh it is not creating anything inside build directory.

**Comment by sunway513** [comment]
The following command is tested to be working for hcrng master branch on ROCm1.5: 
`cd ~ && git clone -b master https://github.com/ROCmSoftwarePlatform/hcRNG.git && cd hcRNG && ./build.sh && dpkg -i build/*.deb`
`cd /opt/rocm/hcrng/lib && ln -s libhiprng_hcc.so libhiprng.so`
